name: Build dev package distributions

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      # we need to fetch the full repo history to use setuptools_scm
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.7"
          python-version: "3.14"
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --all-extras --dev

      - name: Build Python package
        run: uv build
      
      - name: Upload package distributions as artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: |
            dist/
            !dist/.gitignore
